name: Linux Release

on:
  push:
    branches:
      - "master"
      - "continuous-integration"
      - "cross-platform"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
      - "continuous-integration"

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR: ${{ github.workspace }}
  ARTIFACT: qt-planets-build.zip

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Workspace
        run: |
          echo "Workspace: ${{ github.workspace }}"
          echo "Runner temp: ${{ runner.temp }}"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7   # pick Qt 6.7.x
          modules: qtcharts qtmultimedia qttools qtshadertools

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Create build directory
        run: mkdir -p ${{ env.SOURCE_DIR }}/build

      - name: Build
        working-directory: ${{ env.SOURCE_DIR }}/build
        run: |
          qmake -r ${{ env.SOURCE_DIR }}/QtWidgetOpenGl.pro
          make -j$(nproc)

      - name: Package build
        working-directory: ${{ env.SOURCE_DIR }}
        run: |
          7z a ${{ env.ARTIFACT }} build/* -r
          ls -lh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.SOURCE_DIR }}/${{ env.ARTIFACT }}
