name: Linux Release

on:
  push:
    branches:
      - "master"
      - "continuous-integration"
      - "cross-platform"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"
      - "continuous-integration"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.7
          modules: qtcharts qtmultimedia qtshadertools

      - name: Install 7zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: Create build directory
        run: mkdir build

      - name: Build
        working-directory: build
        run: |
          qmake -r ../qt-webcam.pro
          make -j$(nproc)

      - name: Package build
        run: 7z a qt-planets-build.zip build/* -r

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: qt-planets-build
          path: qt-planets-build.zip
